//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORNBusinessLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_DB_FG_Lahore;Persist Security Info=True;User I" +
            "D=sa;Password=sa")]
        public string SAMS_DB_FG_LahoreConnectionString {
            get {
                return ((string)(this["SAMS_DB_FG_LahoreConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_SERVER_FG;Persist Security Info=True;User ID=s" +
            "a;Password=sa")]
        public string SAMS_SERVER_FGConnectionString {
            get {
                return ((string)(this["SAMS_SERVER_FGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM;Persist Security Info=True;User ID=" +
            "sa;Password=sa")]
        public string SAMS_ONLINE_FDMConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM_Current;Persist Security Info=True;" +
            "User ID=sa;Password=sa")]
        public string SAMS_ONLINE_FDM_CurrentConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDM_CurrentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM_TEST;Persist Security Info=True;Use" +
            "r ID=sa;Password=sa")]
        public string SAMS_ONLINE_FDM_TESTConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDM_TESTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM_New;Persist Security Info=True;User" +
            " ID=sa;Password=sa")]
        public string SAMS_ONLINE_FDM_NewConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDM_NewConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDM_BDN;User ID=sa;Password=123")]
        public string SAMS_ONLINE_FDM_BDNConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDM_BDNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_BDN;Persist Security Info=True;User ID=" +
            "sa;Password=sa")]
        public string SAMS_ONLINE_BDNConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_BDNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_SGA;Persist Security Info=True;User ID=" +
            "sa;Password=sa")]
        public string SAMS_ONLINE_SGAConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_SGAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SAMS_ONLINE_FDMPL;Integrated Security=True")]
        public string SAMS_ONLINE_FDMPLConnectionString {
            get {
                return ((string)(this["SAMS_ONLINE_FDMPLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ALI-PC;Initial Catalog=SAMS_ONLINE_FDMPL;Persist Security Info=True;U" +
            "ser ID=sa")]
        public string SAMS_ONLINE_FDMPLConnectionString1 {
            get {
                return ((string)(this["SAMS_ONLINE_FDMPLConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ArshadPOS;Persist Security Info=True;User ID=sa")]
        public string SAMS_ONLINE_FDMPLConnectionString2 {
            get {
                return ((string)(this["SAMS_ONLINE_FDMPLConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FS-DEV-II;Initial Catalog=need;Integrated Security=True")]
        public string needConnectionString {
            get {
                return ((string)(this["needConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=fs-l3\\FASTSERVICES;Initial Catalog=dbASons;Integrated Security=True")]
        public string dbASonsConnectionString {
            get {
                return ((string)(this["dbASonsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.18.221;Initial Catalog=dbNeed;User ID=sa;Password=fast1234")]
        public string dbNeedConnectionString {
            get {
                return ((string)(this["dbNeedConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-9U8QBGM;Initial Catalog=dbneed;User ID=sa")]
        public string dbneedConnectionString1 {
            get {
                return ((string)(this["dbneedConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-N6A34DU;Initial Catalog=dbneed;User ID=sa")]
        public string dbneedConnectionString2 {
            get {
                return ((string)(this["dbneedConnectionString2"]));
            }
        }
    }
}
